#spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:db;Mode=Oracle;DB_CLOSE_ON_EXIT=FALSE
    username: alex
    password:
    driver-class-name: org.h2.Driver

springdoc:
  swagger-ui:
    path: '/'
    disable-swagger-default-url: true
    operations-sorter: alpha
    tags-sorter: alpha